CREATE OR REPLACE  PROCEDURE CREAR_RESERVA(
    P_FECHA IN DATE,
    P_ASIENTOS IN NUMBER,
    P_ESTADO IN NUMBER,
    P_FECHACANCELACION IN DATE,
    P_VARLOCOBRO IN NUMBER,
    P_VALORTOTAL IN NUMBER,
    P_IDCLIENTE IN NUMBER,
    P_IDESTADO IN NUMBER,
    P_IDTARJETA IN NUMBER
)
IS 
BEGIN
    INSERT INTO RESERVA (FECHA, ASIENTOS, ESTADO, FECHACANCELA, VARLOCOBRO, VALORTOTAL, IDCLIENTE, IDESTADO, IDTARJETA)
    VALUES(
        SYSDATE,
        P_ASIENTOS,
        P_ESTADO,
        P_FECHACANCELACION,
        P_VARLOCOBRO,
        P_VALORTOTAL,
        P_IDCLIENTE,
        P_IDESTADO,
        P_IDTARJETA
    );
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'ERROR AL INSERTAR: '|| SQLERRM);
END CREAR_RESERVA;