
--- verificar el container
SHOW CON_NAME
ALTER SESSION SET CONTAINER = XEPDB1;

--Definir tablespace--

CREATE TABLESPACE nombre_del_tablespace
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/mi_tablespace01.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 2G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO
ONLINE;

DROP TABLESPACE nombre_del_tablespace INCLUDING CONTENTS AND DATAFILES;

-- permiso del usuario de app--
GRANT CREATE SESSION TO diego;
SELECT * FROM dba_sys_privs WHERE grantee = 'diego';
ALTER USER diego QUOTA UNLIMITED ON NOMBRE_DEL_TABLESPACE;




------- tablas y secuencias --------

CREATE USER PROYECTO
-- IDENTIFIED BY <password>
;

CREATE TABLE "AVION" 
   (	"IDAVION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MATRICULA" VARCHAR2(45), 
	"ASIENTOS" NUMBER(*,0), 
	 CONSTRAINT "AVION_PK" PRIMARY KEY ("IDAVION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "AVION_PK" ON "AVION" ("IDAVION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "BOLETO" 
   (	"NO_ASIENTO" NUMBER(*,0), 
	"COSTO" NUMBER(38,0), 
	"FECHA" DATE, 
	"IDRESERVA" NUMBER(38,0), 
	"IDPASAJERO" NUMBER(38,0), 
	"IDVUELO" NUMBER(38,0), 
	"PAIS_ORIGEN" VARCHAR2(100), 
	"PAIS_DESTINO" VARCHAR2(100), 
	"IDESTADO" NUMBER(38,0), 
	"IDBOLETO" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_BOLETO".nextval NOT NULL ENABLE, 
	 CONSTRAINT "BOLETO_PK" PRIMARY KEY ("IDBOLETO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MIPROYECTO1" ;

ALTER TABLE "BOLETO" ADD CONSTRAINT "BOLETO_PASAJERO_FK" FOREIGN KEY ("IDPASAJERO")
	  REFERENCES "PASAJERO" ("IDPASAJERO") ENABLE;
  ALTER TABLE "BOLETO" ADD CONSTRAINT "BOLETO_VUELO_FK" FOREIGN KEY ("IDVUELO")
	  REFERENCES "VUELO" ("IDVUELO") ENABLE;
  ALTER TABLE "BOLETO" ADD CONSTRAINT "BOLETO_ESTADO_FK" FOREIGN KEY ("IDESTADO")
	  REFERENCES "ESTADO" ("IDESTADO") ENABLE;

CREATE UNIQUE INDEX "BOLETO_PK" ON "BOLETO" ("IDBOLETO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "CLIENTE" 
   (	"IDCLIENTE" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_CLIENTE".nextval NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(45), 
	"APELLIDO" VARCHAR2(40), 
	"TELEFONO" VARCHAR2(45), 
	"DPI" VARCHAR2(20), 
	 CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "CLIENTE_PK" ON "CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "ESCALA" 
   (	"IDESCALA" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_ESCALA".nextval, 
	"IDPAIS" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "ESTADO" 
   (	"IDESTADO" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_ESTADO".nextval NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "ESTADO_PK" PRIMARY KEY ("IDESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "ESTADO_PK" ON "ESTADO" ("IDESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "PAIS" 
   (	"IDPAIS" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_PAIS".nextval NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(45), 
	 CONSTRAINT "PAIS_PK" PRIMARY KEY ("IDPAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "PAIS_PK" ON "PAIS" ("IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "PASAJERO" 
   (	"IDPASAJERO" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_PASAJERO".nextval NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(45), 
	"DPI" VARCHAR2(20), 
	"VACUNAS" NUMBER(*,0), 
	 CONSTRAINT "PASAJERO_PK" PRIMARY KEY ("IDPASAJERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "PASAJERO_PK" ON "PASAJERO" ("IDPASAJERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "PORCENTAJE" 
   (	"IDPORCENTAJE" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_PORCENTAJE".nextval NOT NULL ENABLE, 
	"PORCENTAJECOL" VARCHAR2(100), 
	"DIAS" VARCHAR2(100), 
	 CONSTRAINT "PORCENTAJE_PK" PRIMARY KEY ("IDPORCENTAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "PORCENTAJE_PK" ON "PORCENTAJE" ("IDPORCENTAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "RESERVA" 
   (	"IDRESERVA" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_RESERVA".nextval NOT NULL ENABLE, 
	"FECHA" DATE, 
	"ASIENTOS" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	"FECHACANCELA" DATE, 
	"VARLOCOBRO" NUMBER(*,0), 
	"VALORTOTAL" NUMBER(38,0), 
	"IDCLIENTE" NUMBER(38,0), 
	"IDESTADO" NUMBER(38,0), 
	 CONSTRAINT "RESERVA_PK" PRIMARY KEY ("IDRESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MIPROYECTO1" ;

ALTER TABLE "RESERVA" ADD CONSTRAINT "RESERVA_CLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "CLIENTE" ("IDCLIENTE") ENABLE;
  ALTER TABLE "RESERVA" ADD CONSTRAINT "RESERVA_ESTADO_FK" FOREIGN KEY ("IDESTADO")
	  REFERENCES "ESTADO" ("IDESTADO") ENABLE;

CREATE UNIQUE INDEX "RESERVA_PK" ON "RESERVA" ("IDRESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "TARJETA" 
   (	"IDTARJETA" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_TARJETA".nextval NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	"IDCLIENTE" NUMBER(38,0), 
	 CONSTRAINT "TARJETA_PK" PRIMARY KEY ("IDTARJETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

ALTER TABLE "TARJETA" ADD CONSTRAINT "TARJETA_CLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "CLIENTE" ("IDCLIENTE") ENABLE;

CREATE UNIQUE INDEX "TARJETA_PK" ON "TARJETA" ("IDTARJETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;
;

CREATE TABLE "VUELO" 
   (	"IDVUELO" NUMBER(38,0) DEFAULT "PROYECTO"."SEQ_VUELO".nextval NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	"DISPONIBILIDAD" VARCHAR2(100), 
	"FECHA" DATE, 
	"IDAVION" NUMBER(38,0), 
	"IDPAIS" NUMBER(38,0), 
	"PAIS_ORIGEN" NUMBER(*,0), 
	"PAIS_DESTINO" NUMBER(*,0), 
	 CONSTRAINT "VUELO_PK" PRIMARY KEY ("IDVUELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;

CREATE UNIQUE INDEX "VUELO_PK" ON "VUELO" ("IDVUELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIPROYECTO1" ;
;

CREATE SEQUENCE PROYECTO."ISEQ$$_75888" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_BOLETO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_CLIENTE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_ESCALA INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_ESTADO INCREMENT BY 1 MINVALUE 3 MAXVALUE 999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_PAIS INCREMENT BY 1 MINVALUE 4 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_PASAJERO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_PORCENTAJE INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_RESERVA INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_TARJETA INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PROYECTO.SEQ_VUELO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;
